<!DOCTYPE html>
<html>
<head>
    <title>This Email generated by Sneakerx.com</title>
</head>
<body>
<h1>{{ $user['name'] }}</h1>
<p>{{ $user['info'] }}</p>
<p>Please check the dashboard for more information.</p>
</body>
</html>
